<?php

/*
 *	Updated by: Frederik Betz (frederik.betz@bonsum.de)
 *	On: Friday, 03-Jul-15 09:45:23 UTC
 *	Via web admin-interface from: 91.65.97.81
 */

return array (
  'article_titles' =>
  array (
    't0' => '<strong>Was bei Bonsum anders und neu ist?<br>Der Kunde wird nicht zum gl&auml;sernen Konsumenten</strong>',
    't1' => '1. Deine Daten, nicht unsere!',
    't2' => '2. Nutzung Deiner Daten f&uuml;r individuelle Angebote, Werbung und Marktforschung / K&auml;uferprofile',
    't3' => '3. Keine &Uuml;bermittlung Deiner Daten an Dritte',
    't4' => '4. L&ouml;schung der Daten',
    't5' => '5. E-Mails aus und in Europa',
    't6' => '6. Verwendung von Social Plugins',
    't7' => '7. Datenschutzerkl&auml;rung f&uuml;r Kunden bzgl. Webtracking',
    't8' => '8. Fragen zum Datenschutz',
  ),
  'article_body' =>
  array (
    'p0' => '<strong>Datenschutz</strong>: Für die Teilnahme am Bonsum Programm, das von der Bonsum UG (haftungsbeschränkt) (nachfolgend „Bonsum” genannt) betrieben wird, gelten die nachfolgenden Datenschutz-Hinweise.',
    'p1' => 'Wenn Du am Programm von Bonsum teilnehmen möchtest, wird für die <strong><span>Eröffnung eines Kontos lediglich Deine E-Mail-Adresse</span></strong>, ein frei wählbarer Benutzername und ein Passwort benötigt („Stammdaten”). Diese Stammdaten werden direkt bei Bonsum abgegeben oder bei der Anmeldung über einen Partner bei Bonsum von diesem an Bonsum übermittelt. <strong><span>Wenn Du Bonets sammelst, tun wir alles dafür, so wenig Daten </span></strong><strong><span>wie möglich </span></strong><strong><span>zu generieren</span></strong>. So werden nur die Daten erfasst und vom Partner an Bonsum übermittelt, die unbedingt notwendig sind, um Dir die Bonets auf Deinem Konto gutzuschreiben (Transaktionsdaten). Transaktionsdaten sind Deine E-Mail Adresse bzw. Teilnehmerkennung, die Anzahl der Bonets oder der getätigte Umsatz, das Buchungsdatum sowie die Kennzeichnung des Partners und der Promotion, an der Du teilgenommen hast. Wenn Du an anderen Dienstleistungen wie „Bonsumer des Monats“ teilnimmst, erhebt Bonsum zusätzlich einige Angaben zu Deiner Person und zu Deinen Interessen („freiwillige Angaben”). Diese Angaben sind freiwillig und kommen von Dir.<strong> Bei der Einlösung der Bonets erfasst Bonsum keine Adresse.</strong>',
    'p2' => 'Wir erstellen keine Käuferprofile und geben Deine Daten nie an Dritte weiter. <span style="text-decoration: underline;">Ebenso findest Du auf unsere Seite im Vergleich zu anderen Anbietern keine Marketingdienstleistungen. Dies kommt daher, dass wir Deine Daten nicht zu Marketingzwecken nutzen.</span> ',
    'p3' => 'Wir garantieren, dass keine persönlichen Daten an Dritte außerhalb unserer Plattform weitergegeben oder verkauft werden.<br /> <strong><br /> </strong>',
    'p4' => 'Die bei Bonsum gespeicherten Daten eines Teilnehmers werden gelöscht, wenn sie zur Durchführung des Programms oder zur Erfüllung gesetzlicher Pflichten nicht mehr benötigt werden.',
    'p5_0' => 'Wir benutzen zum Versenden und Empfangen all unserer E-Mails den Anbieter <a href="https://de.mailjet.com/" target="_blank" rel="nofollow">mailjet</a>. Dieser stellt eine europäische Alternative zu US Anbietern dar. Die Daten werden dabei laut Unternehmensangaben auf der größten und sichersten Hosting-Firma Europas und der viertgrößtem weltweit (Netcraft Januar 2012) gehostet. Das dabei genutzte System entspricht den ‘Safe Harbor’-Richtlinien der EU Data Protection Directive. Dabei bleibt Bonsum Besitzer der Daten, die mit unserem Benutzerkonto verbunden sind, inklusive der Transaktions- und Kundendaten. Mailjet bietet nur den Service an und stellen die Integrität Deiner Daten sicher.',
    'p5_1' => 'Dabei werden automatisch verschlüsselte Backups genutzt, um sicherzustellen, dass Deine Online-Daten immer sicher und vollständig sind.',
    'p6_0' => '6.1. Facebook<br> Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Die Facebook-Plugins erkennst Du an dem Facebook-Logo oder dem „Gefällt mir” auf unserer Seite. Eine Übersicht über die Facebook-Plugins findest Du hier: <a href="http://developers.facebook.com/docs/plugins/" target="_blank" rel="nofollow">http://developers.facebook.com/docs/plugins/</a>.',
    'p6_1' => 'Wenn Du den Facebook „Gefällt mir”-Button anklickst, während Du in Deinem Facebook-Account eingeloggt bist, kannst Du die Inhalte unserer Seiten auf Dein Facebook-Profil verlinken. Dadurch kann Facebook den Besuch unserer Seiten Deinem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu findest Du in der Datenschutzerklärung von Facebook unter <a href="http://de-de.facebook.com/policy.php" target="_blank" rel="nofollow">http://de-de.facebook.com/policy.php</a>. Wenn Du nicht wünschst, dass Facebook den Besuch unserer Seiten Deinem Facebook-Nutzerkonto zuordnen kann, klick hier einfach nicht drauf.',
    'p6_2' => '6.2. YouTube<br /> Auf unseren Seiten sind Videos von YouTube eingebunden. Wir ermöglichen nur die Verbindung zu YouTube. YouTube ist ein Angebot von Google Inc. Zweck und Umfang der Datenerhebung und -nutzung durch Google sowie Deine Rechte und Einstellungsmöglichkeiten zum Schutz als YouTube-Kunde entnimm bitte den Datenschutzhinweisen von YouTube unter <a href="http://www.youtube.com/t/privacy" target="_blank" rel="nofollow">http://www.youtube.com/t/privacy</a>.',
    'p7_0' => 'Bonsum nimmt den Schutz Deiner persönlichen Daten überaus ernst und wir halten uns an die Regeln der Datenschutzgesetze.',
    'p7_1' => '7.1. Erfasste Daten für das Webtracking<br> <strong>Unsere Website verwendet bewusst nicht Google Analytics aus den USA sondern die europäsiche Alternative Piwik </strong>, dabei handelt es sich um einen sogenannten Webanalysedienst. Piwik verwendet sog. „Cookies”, das sind Textdateien, die auf Deinem Computer gespeichert werden und die unsererseits eine Analyse der Benutzung der Webseite ermöglichen. Zu diesem Zweck werden die durch den Cookie erzeugten Nutzungsinformationen (einschließlich Deiner gekürzten IP-Adresse) an unseren Server übertragen und zu Nutzungsanalysezwecken gespeichert, was der Webseitenoptimierung unsererseits dient. Deine IP-Adresse wird bei diesem Vorgang umge­hend anony­mi­siert, so dass Du als Nutzer für uns anonym bleibst. Die durch den Cookie erzeugten Informationen über Deine Benutzung dieser Webseite werden nicht an Dritte weitergegeben. Du kannst die Verwendung der Cookies durch eine entsprechende Einstellung Deiner Browser Software verhindern, es kann jedoch sein, dass Du in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen kannst und wir Dir die Bonets nicht zuordnen können. Wenn Du mit der Spei­che­rung und Aus­wer­tung die­ser Daten aus Deinem Besuch nicht ein­ver­stan­den bist, kannst Du der Spei­che­rung und Nut­zung nachfolgend per Maus­klick jederzeit wider­spre­chen. In diesem Fall wird in Deinem Browser ein sog. Opt-Out-Cookie abgelegt, was zur Folge hat, dass Piwik kei­ner­lei Sit­zungs­da­ten erhebt. <strong>Achtung</strong>: Wenn Du Cookies löschst, so hat dies zur Folge, dass auch das Opt-Out-Cookie gelöscht wird und ggf. von Dir erneut aktiviert werden muss. Du kannst dich hier entscheiden, ob in Deinem Browser ein eindeutiger Webanalyse-Cookie abgelegt werden darf, um dem Betreiber der Webseite die Erfassung und Analyse verschiedener statistischer Daten zu Optimierung der Nutzung zu ermöglichen.',
    'p7_2' => 'Klicken Sie hier, um ein Cookie zu setzen, damit Piwik Ihre Besuche auf www.netstatz.de ignoriert. ',
    'p7_3' => '7.2. IP-Adresse<br /> Die IP-Adresse wird bei jeder Serveranfrage übertragen, damit der Server weiß, wohin die Antwort gesendet werden muss. Die IP-Adresse erhält jeder von einem Internet-Service-Provider (ISP), sobald er sich mit dem Internet verbindet und der ISP kann nachvollziehen, welche IP-Adresse zu welchem Zeitpunkt welchem seiner Kunden zugeordnet wurde. Solange die IP-Adresse gespeichert wird, kann über den Umweg des ISPs theoretisch die Identität des Anschlussinhabers ermittelt werden. Wir und unser Statistikdienstleister speichern die IP-Adresse daher nur in gekürzter (anonymisierter) Form und verwenden sie nur zur Session Erkennung und für die Abwehr von Attacken. Die IP-Adresse wird dann umgehend wieder gelöscht, so dass die erfassten Daten dann anonym sind und selbst über den Umweg des ISPs keine Zuordnung zur Identität des Nutzers mehr möglich ist.',
    'p7_4' => '7.3. Cookies<br /> <strong>Unsere Internetseiten verwenden an mehreren Stellen sogenannte Cookies. Sie dienen dazu, die Bonets Deinen Käufen zuzuordnen</strong>. Cookies sind kleine Textdateien, die auf Deinem Rechner abgelegt werden und die Dein Browser speichert. <strong>Die Cookies enthalten keine persönlichen Daten. Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen.</strong> Die meisten der von uns verwendeten Cookies sind so genannte „Session-Cookies“, die gelöscht werden, wenn sie Deine Browsersitzung beenden. Daneben gibt es einige langlebige Cookies mittels derer wir Dich als Besucher wiedererkennen.<br />
      Cookies richten auf Deinem Rechner keinen Schaden an und enthalten keine Viren. Folgende Cookies werden gesetzt:<br />
      · Session Cookie (für Session-Erkennung, Lebensdauer: eine Session)<br />
      · Langzeit-Cookie (zur Erkennung Neu-/Stammkunde, Lebensdauer: 6 Monate)<br />
      · Opt-out-Cookie (bei Widerspruch gegen das Tracking, Lebensdauer: 60 Monate)<br />
      · Opt-in-Cookie (zur Erweiterung des Langzeit-Cookies, Lebensdauer: 12 Monate) In Deinen Browsereinstellungen kannst Du festlegen, ob Cookies gesetzt werden dürfen oder nicht.',
    'p7_5' => '7.4. Widerruf bei Nutzung von Cookies<br />
      Nach §15 des Telemediengesetzes können Webseitenbesucher der Datenspeicherung pseudo-anonymisiert erfassten Besucherdaten widersprechen, so dass sie in Zukunft auf dieser Webseite nicht mehr erhoben (erfasst) werden.',
    'p7_6' => '7.5. Zustimmung zur erweiterten Cookie Nutzung<br />
      Unser Statistikdienstleister verwendet sogenannte Langzeit-Cookies wenn Du unsere Internet-Seiten besuchst. Dadurch ist es möglich Dich ggf. bei einem erneuten Besuch unserer Webseite wiederzuerkennen. Die Wiedererkennung erfolgt mit diesen Cookies zur Optimierung der Inhalte unserer Webseite. In der Standardeinstellung werden von uns nur Cookies mit einer Laufzeit von maximal 6 Monaten zugelassen. Für eine langfristige Optimierung unserer Webseite und zur gezielten Bereitstellung von Inhalten oder Nutzerinformationen benötigen wir aber auch Cookie-Informationen über einen längeren Zeitraum. Mit der erweiterten Cookie Nutzung stimmst Du einer Verlängerung der Haltbarkeit des gesetzten Langzeit-Cookies auf maximal 12 Monate zu.<br />
      <strong><br />
      </strong>',
    'p8_0' => 'Wenn Du Fragen oder Anregungen zum Datenschutz bei Bonsum hast, kannst Du Dich jederzeit gerne unter <a href="mailto:meinedaten@bonsum.de">meinedaten@bonsum.de</a> an unser Team wenden.',
    'p8_1' => 'Stand: Mai 2015',
  ),
);
